universe = vanilla
executable = /storage/gpfs_data/juno/junofs/users/gferrante/TAO/data_analysis/energy_spectrum/launch_plot_resolution_vs_run.sh
log = /storage/gpfs_data/juno/junofs/users/gferrante/TAO/data_analysis/energy_spectrum/out-err/launch_plot_resolution_vs_run.log
output = /storage/gpfs_data/juno/junofs/users/gferrante/TAO/data_analysis/energy_spectrum/out-err/launch_plot_resolution_vs_run.out
error = /storage/gpfs_data/juno/junofs/users/gferrante/TAO/data_analysis/energy_spectrum/out-err/launch_plot_resolution_vs_run.err
+MaxRuntime = 3600
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT
+SingularityImage = false
queue 1
