#ifndef ORSACLASSIFICATION_OUTPUTMANAGER_H
#define ORSACLASSIFICATION_OUTPUTMANAGER_H

// OutputManager.h
//
// Orchestrates the centralized allocation, branch definition, and persistent data
// serialization for all ROOT tree structures generated by analytical correlation
// operations. Output channels are distinctly identified by unique alphanumeric
// rule identifiers, ensuring strict separation of disparate physics signatures.
//
// The manager utilizes a singular, volatile memory buffer to temporarily aggregate
// event properties prior to serialization. Dedicated serialization subroutines
// subsequently bind this buffer to the corresponding dynamic branch schemas before
// final propagation to disk. Optimization dictates that structural branch creation
// strictly follows a lazy-initialization paradigm, instantiating topology only
// when the corresponding output stream initially receives processed data.
//
// Embedded metadata features rigorously serialize the primary analysis configuration
// and complete nomenclature tag maps directly into the output envelope, ensuring
// long-term reproducibility and structural self-documentation.

#include "Candidate.h"
#include "MuonManager.h"
#include <string>
#include <unordered_map>
#include <map>
#include <functional>

class TTree;  // forward declaration (from ROOT)

namespace Orsa {

    // All output variables for a single tree entry.
    // Field naming convention:
    //   _p = prompt candidate, _d = delayed candidate
    //   t  = time [ns], E = energy [MeV], x/y/z = position [mm]
    //   dt = time difference [ns], dr = spatial separation [mm]
    struct OutputVars {
        // Prompt candidate.
        int64_t t_p = 0;
        double E_p = 0, x_p = 0, y_p = 0, z_p = 0;

        // Delayed candidate.
        int64_t t_d = 0;
        double E_d = 0, x_d = 0, y_d = 0, z_d = 0;

        // Pair kinematics.
        double dt = 0;        // t_d - t_p [ns]
        double dr = 0;        // 3D distance [mm]

        // Muon distance to the prompt (simple point-to-point).
        int64_t dt_mu = -1;   // time to closest muon [ns]
        double dist_mu = -1;  // distance to closest muon [mm]

        // Closest muon by time: track-level distance, dt, and WP track count.
        double dist_track_time = -1;
        int64_t dt_mu_time = -1;
        int ntracks_time = 0;

        // Closest muon by distance: track-level distance, dt, and WP track count.
        double dist_track_dist = -1;
        int64_t dt_mu_dist = -1;
        int ntracks_dist = 0;

        // Per-event tags stored as variable-length vectors of active tag IDs.
        std::vector<int> tags_p, tags_d;

        // Isolation counters (filled by StandardPairRule for pairs).
        int iso_before = 0, iso_between = 0, iso_after = 0;

        // Calibration statistics for prompt.
        int nFired_p = 0;
        float totalPE_p = 0, max_pmt_PE_p = 0, second_max_pmt_PE_p = 0, charge_ratio_p = 0;
        bool is_flasher_p = false, is_lowEMuon_p = false;
        float ntq_mean_p = 0, ntq_std_p = 0;
        float hit_t_mean_p = 0, hit_t_std_p = 0;
        float hit_q_mean_p = 0, hit_q_std_p = 0;

        // Calibration statistics for delayed.
        int nFired_d = 0;
        float totalPE_d = 0, max_pmt_PE_d = 0, second_max_pmt_PE_d = 0, charge_ratio_d = 0;
        bool is_flasher_d = false, is_lowEMuon_d = false;
        float ntq_mean_d = 0, ntq_std_d = 0;
        float hit_t_mean_d = 0, hit_t_std_d = 0;
        float hit_q_mean_d = 0, hit_q_std_d = 0;

        // Accidental-pair time and spatial offsets applied to the prompt.
        int64_t acc_shift_t = 0;
        double acc_shift_x = 0, acc_shift_y = 0, acc_shift_z = 0;

        void reset() { *this = OutputVars{}; }
    };

    // Settings controlling which branch groups are booked for a given tree.
    // The `path` field overrides the default "output/<name>" tree location.
    struct OutputSettings {
        std::string path;
        bool saveMuonInfo = true;
        bool saveCalibInfo = true;
        bool saveTags = true;
    };

    class OutputManager {
    public:
        OutputManager(TTree* defaultTree = nullptr);
        ~OutputManager();

        // Set the TTree factory callback.  Called once during OrsaAlg::initialize().
        // The callback wraps SNiPER's RootWriter::bookTree() and returns
        // a TTree pointer for the given (path, title) pair.
        using TreeBooker = std::function<TTree*(const std::string&, const std::string&)>;
        void setTreeBooker(TreeBooker booker) { m_booker = booker; }

        // Override default output settings for a specific tree.
        void setTreeSettings(const std::string& key, const OutputSettings& settings) {
            m_treeSettings[key] = settings;
        }

        // Create or retrieve a tree for the given key.
        TTree* getOrBookTree(const std::string& key, const std::string& title = "");

        // Fill a pair entry (prompt + delayed).
        // t_off / s_off: time and spatial offsets applied to the prompt for
        //   accidental pairs (zero for signal pairs).
        void fillPair(const std::string& treeName, const Candidate& prompt, const Candidate& delayed,
                      const MuonManager* mm,
                      int64_t t_off = 0, const TVector3& s_off = {0,0,0},
                      bool isAccidental = false);

        // Fill a single-event entry (used by CategoryTagRule and diagnostics).
        void fillSingle(const std::string& treeName, const Candidate& cand,
                        const MuonManager* mm);

        // Persist the full JSON configuration string and the tag name->ID mapping
        // as branches in a "UserMetadata" TTree.
        void saveMetadata(const std::string& config, const std::map<std::string, int>& tagMap);

    private:
        TreeBooker m_booker;
        TTree* m_defaultTree = nullptr;
        std::unordered_map<std::string, TTree*> m_trees;
        std::unordered_map<std::string, bool> m_initialized;    // tracks which trees have been branched
        std::unordered_map<std::string, OutputSettings> m_treeSettings;
        OutputSettings m_defaultSettings;
        OutputVars m_vars;  // shared fill buffer

        // Create branches on a tree, choosing schema based on whether
        // this is a pair tree or single-event tree.
        void ensureBranches(TTree* tree, bool isPair);
    };

}

#endif // ORSACLASSIFICATION_OUTPUTMANAGER_H
